# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Citizen3540
version:      0.6
version_from: Citizen3540.pm
installdirs:  perl
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
